name: Hello World
on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say Hi!
        run: echo "Hi world!"
      - name: Tell Date
        run: date
      - name: Dir Contents
        run: ls -l
